version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/testing/__api.testing.octopii.cloud
hooks:
  ApplicationStop:
    - location: scripts/clean_up.sh
      timeout: 300
      runas: ubuntu
  BeforeInstall:
    - location: scripts/clean_up.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/composer_install.sh
      timeout: 300
      runas: ubuntu
    - location: scripts/env_setup.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_services.sh
      timeout: 300
      runas: ubuntu
  ValidateService:
    - location: scripts/validate_deployment.sh
      timeout: 300
      runas: ubuntu
